### PR TITLE
Add license to gemspec.

### PR DESCRIPTION
**Pull request by reiz**

### CODE REVIEW

**Comment by sbleon** [comment]
Thanks, @reiz !

**Comment by sbleon** [comment]
I've released v0.2.5 including this change.

**Comment by reiz** [comment]
@sbleon Thanks for merging. Tomorrow the new release will show up at [VersionEye](https://www.versioneye.com/ruby/utf8-cleaner/0.2.4) and I don't have to add the license manually anymore :-) You helped me a lot.

**Comment by sbleon** [comment]
You’re welcome!

**Pull request merged**
